/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ICreateCompany
 */
export interface ICreateCompany {
    /**
     * Name of the client. This will help you identify it later.
     * @type {string}
     * @memberof ICreateCompany
     */
    name: string;
    /**
     * The name of the person of contact for the client. This person is also the recipient of the proceeds from primary sale and royalty from secondary sales.
     * @type {string}
     * @memberof ICreateCompany
     */
    poc: string;
    /**
     * The email of the person of contact for the client. This wallet linked to this email will be used to credit the proceeds from primary sale and royalty from secondary sales.
     * @type {string}
     * @memberof ICreateCompany
     */
    pocEmail: string;
}

/**
 * Check if a given object implements the ICreateCompany interface.
 */
export function instanceOfICreateCompany(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "poc" in value;
    isInstance = isInstance && "pocEmail" in value;

    return isInstance;
}

export function ICreateCompanyFromJSON(json: any): ICreateCompany {
    return ICreateCompanyFromJSONTyped(json, false);
}

export function ICreateCompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ICreateCompany {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'poc': json['poc'],
        'pocEmail': json['pocEmail'],
    };
}

export function ICreateCompanyToJSON(value?: ICreateCompany | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'poc': value.poc,
        'pocEmail': value.pocEmail,
    };
}

