/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface IGetWalletResp
 */
export interface IGetWalletResp {
  /**
   *
   * @type {Array<any>}
   * @memberof IGetWalletResp
   */
  wallets: Array<any>;
  /**
   *
   * @type {string}
   * @memberof IGetWalletResp
   */
  lastId: string;
}

/**
 * Check if a given object implements the IGetWalletResp interface.
 */
export function instanceOfIGetWalletResp(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'wallets' in value;
  isInstance = isInstance && 'lastId' in value;

  return isInstance;
}

export function IGetWalletRespFromJSON(json: any): IGetWalletResp {
  return IGetWalletRespFromJSONTyped(json, false);
}

export function IGetWalletRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): IGetWalletResp {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    wallets: json['wallets'],
    lastId: json['lastId'],
  };
}

export function IGetWalletRespToJSON(value?: IGetWalletResp | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    wallets: value.wallets,
    lastId: value.lastId,
  };
}
