/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface IListTokenGroupDataResp
 */
export interface IListTokenGroupDataResp {
  /**
   *
   * @type {Array<any>}
   * @memberof IListTokenGroupDataResp
   */
  tokenGroups: Array<any>;
  /**
   *
   * @type {string}
   * @memberof IListTokenGroupDataResp
   */
  lastId: string;
}

/**
 * Check if a given object implements the IListTokenGroupDataResp interface.
 */
export function instanceOfIListTokenGroupDataResp(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'tokenGroups' in value;
  isInstance = isInstance && 'lastId' in value;

  return isInstance;
}

export function IListTokenGroupDataRespFromJSON(json: any): IListTokenGroupDataResp {
  return IListTokenGroupDataRespFromJSONTyped(json, false);
}

export function IListTokenGroupDataRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): IListTokenGroupDataResp {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    tokenGroups: json['tokenGroups'],
    lastId: json['lastId'],
  };
}

export function IListTokenGroupDataRespToJSON(value?: IListTokenGroupDataResp | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    tokenGroups: value.tokenGroups,
    lastId: value.lastId,
  };
}
