/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface IMintTokenGroupData
 */
export interface IMintTokenGroupData {
  /**
   *
   * @type {any}
   * @memberof IMintTokenGroupData
   */
  company?: any | null;
  /**
   *
   * @type {string}
   * @memberof IMintTokenGroupData
   */
  tokenGroupDataId: string;
  /**
   *
   * @type {Array<string>}
   * @memberof IMintTokenGroupData
   */
  destinations: Array<string>;
  /**
   *
   * @type {Array<number>}
   * @memberof IMintTokenGroupData
   */
  amounts?: Array<number>;
}

/**
 * Check if a given object implements the IMintTokenGroupData interface.
 */
export function instanceOfIMintTokenGroupData(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'tokenGroupDataId' in value;
  isInstance = isInstance && 'destinations' in value;

  return isInstance;
}

export function IMintTokenGroupDataFromJSON(json: any): IMintTokenGroupData {
  return IMintTokenGroupDataFromJSONTyped(json, false);
}

export function IMintTokenGroupDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): IMintTokenGroupData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    company: !exists(json, 'company') ? undefined : json['company'],
    tokenGroupDataId: json['tokenGroupDataId'],
    destinations: json['destinations'],
    amounts: !exists(json, 'amounts') ? undefined : json['amounts'],
  };
}

export function IMintTokenGroupDataToJSON(value?: IMintTokenGroupData | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    company: value.company,
    tokenGroupDataId: value.tokenGroupDataId,
    destinations: value.destinations,
    amounts: value.amounts,
  };
}
