/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IMintData
 */
export interface IMintData {
    /**
     * 
     * @type {any}
     * @memberof IMintData
     */
    company?: any | null;
    /**
     * The tokenDataId of the tokenData to mint.
     * @type {string}
     * @memberof IMintData
     */
    tokenDataId: string;
    /**
     * The array of walletIds to mint the tokens into.
     * @type {Array<string>}
     * @memberof IMintData
     */
    destinations: Array<string>;
    /**
     * The array of amount of tokens to mint to the destination wallets.
     * @type {Array<number>}
     * @memberof IMintData
     */
    amounts?: Array<number>;
}

/**
 * Check if a given object implements the IMintData interface.
 */
export function instanceOfIMintData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tokenDataId" in value;
    isInstance = isInstance && "destinations" in value;

    return isInstance;
}

export function IMintDataFromJSON(json: any): IMintData {
    return IMintDataFromJSONTyped(json, false);
}

export function IMintDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): IMintData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'company': !exists(json, 'company') ? undefined : json['company'],
        'tokenDataId': json['tokenDataId'],
        'destinations': json['destinations'],
        'amounts': !exists(json, 'amounts') ? undefined : json['amounts'],
    };
}

export function IMintDataToJSON(value?: IMintData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'company': value.company,
        'tokenDataId': value.tokenDataId,
        'destinations': value.destinations,
        'amounts': value.amounts,
    };
}

