/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface IRefreshToken
 */
export interface IRefreshToken {
  /**
   *
   * @type {any}
   * @memberof IRefreshToken
   */
  company?: any | null;
  /**
   * Refresh token stored in the client's front-end
   * @type {string}
   * @memberof IRefreshToken
   */
  token: string;
}

/**
 * Check if a given object implements the IRefreshToken interface.
 */
export function instanceOfIRefreshToken(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'token' in value;

  return isInstance;
}

export function IRefreshTokenFromJSON(json: any): IRefreshToken {
  return IRefreshTokenFromJSONTyped(json, false);
}

export function IRefreshTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): IRefreshToken {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    company: !exists(json, 'company') ? undefined : json['company'],
    token: json['token'],
  };
}

export function IRefreshTokenToJSON(value?: IRefreshToken | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    company: value.company,
    token: value.token,
  };
}
