/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface IRefreshTokenResponse
 */
export interface IRefreshTokenResponse {
  /**
   *
   * @type {string}
   * @memberof IRefreshTokenResponse
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof IRefreshTokenResponse
   */
  accessToken: string;
  /**
   *
   * @type {string}
   * @memberof IRefreshTokenResponse
   */
  refreshToken: string;
}

/**
 * Check if a given object implements the IRefreshTokenResponse interface.
 */
export function instanceOfIRefreshTokenResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;
  isInstance = isInstance && 'accessToken' in value;
  isInstance = isInstance && 'refreshToken' in value;

  return isInstance;
}

export function IRefreshTokenResponseFromJSON(json: any): IRefreshTokenResponse {
  return IRefreshTokenResponseFromJSONTyped(json, false);
}

export function IRefreshTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IRefreshTokenResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    accessToken: json['accessToken'],
    refreshToken: json['refreshToken'],
  };
}

export function IRefreshTokenResponseToJSON(value?: IRefreshTokenResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    accessToken: value.accessToken,
    refreshToken: value.refreshToken,
  };
}
