/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ISignMarketplaceOrderString
 */
export interface ISignMarketplaceOrderString {
  /**
   *
   * @type {string}
   * @memberof ISignMarketplaceOrderString
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ISignMarketplaceOrderString
   */
  form: string;
}

/**
 * Check if a given object implements the ISignMarketplaceOrderString interface.
 */
export function instanceOfISignMarketplaceOrderString(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;
  isInstance = isInstance && 'form' in value;

  return isInstance;
}

export function ISignMarketplaceOrderStringFromJSON(json: any): ISignMarketplaceOrderString {
  return ISignMarketplaceOrderStringFromJSONTyped(json, false);
}

export function ISignMarketplaceOrderStringFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ISignMarketplaceOrderString {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    form: json['form'],
  };
}

export function ISignMarketplaceOrderStringToJSON(value?: ISignMarketplaceOrderString | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    form: value.form,
  };
}
