/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ITokenExternalMetadataUri } from './ITokenExternalMetadataUri';
import {
    ITokenExternalMetadataUriFromJSON,
    ITokenExternalMetadataUriFromJSONTyped,
    ITokenExternalMetadataUriToJSON,
} from './ITokenExternalMetadataUri';
import type { ITokenMetadata } from './ITokenMetadata';
import {
    ITokenMetadataFromJSON,
    ITokenMetadataFromJSONTyped,
    ITokenMetadataToJSON,
} from './ITokenMetadata';

/**
 * 
 * @export
 * @interface ITokenDataMetadata
 */
export interface ITokenDataMetadata {
    /**
     * 
     * @type {string}
     * @memberof ITokenDataMetadata
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ITokenDataMetadata
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ITokenDataMetadata
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof ITokenDataMetadata
     */
    externalUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ITokenDataMetadata
     */
    animationUrl?: string;
    /**
     * 
     * @type {any}
     * @memberof ITokenDataMetadata
     */
    attributes?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ITokenDataMetadata
     */
    url: string;
}

/**
 * Check if a given object implements the ITokenDataMetadata interface.
 */
export function instanceOfITokenDataMetadata(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function ITokenDataMetadataFromJSON(json: any): ITokenDataMetadata {
    return ITokenDataMetadataFromJSONTyped(json, false);
}

export function ITokenDataMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ITokenDataMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'image': !exists(json, 'image') ? undefined : json['image'],
        'externalUrl': !exists(json, 'external_url') ? undefined : json['external_url'],
        'animationUrl': !exists(json, 'animation_url') ? undefined : json['animation_url'],
        'attributes': !exists(json, 'attributes') ? undefined : json['attributes'],
        'url': json['url'],
    };
}

export function ITokenDataMetadataToJSON(value?: ITokenDataMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'image': value.image,
        'external_url': value.externalUrl,
        'animation_url': value.animationUrl,
        'attributes': value.attributes,
        'url': value.url,
    };
}

