/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ITokenDataMetadata } from './ITokenDataMetadata';
import {
  ITokenDataMetadataFromJSON,
  ITokenDataMetadataFromJSONTyped,
  ITokenDataMetadataToJSON,
} from './ITokenDataMetadata';

/**
 *
 * @export
 * @interface IUpdateTokenGroupData
 */
export interface IUpdateTokenGroupData {
  /**
   *
   * @type {any}
   * @memberof IUpdateTokenGroupData
   */
  company?: any | null;
  /**
   *
   * @type {string}
   * @memberof IUpdateTokenGroupData
   */
  tokenGroupDataId: string;
  /**
   *
   * @type {string}
   * @memberof IUpdateTokenGroupData
   */
  reserveTokenDataId: string;
  /**
   *
   * @type {number}
   * @memberof IUpdateTokenGroupData
   */
  reserveTokenDataAmount: number;
  /**
   *
   * @type {ITokenDataMetadata}
   * @memberof IUpdateTokenGroupData
   */
  metadata: ITokenDataMetadata;
}

/**
 * Check if a given object implements the IUpdateTokenGroupData interface.
 */
export function instanceOfIUpdateTokenGroupData(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'tokenGroupDataId' in value;
  isInstance = isInstance && 'reserveTokenDataId' in value;
  isInstance = isInstance && 'reserveTokenDataAmount' in value;
  isInstance = isInstance && 'metadata' in value;

  return isInstance;
}

export function IUpdateTokenGroupDataFromJSON(json: any): IUpdateTokenGroupData {
  return IUpdateTokenGroupDataFromJSONTyped(json, false);
}

export function IUpdateTokenGroupDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): IUpdateTokenGroupData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    company: !exists(json, 'company') ? undefined : json['company'],
    tokenGroupDataId: json['tokenGroupDataId'],
    reserveTokenDataId: json['reserveTokenDataId'],
    reserveTokenDataAmount: json['reserveTokenDataAmount'],
    metadata: ITokenDataMetadataFromJSON(json['metadata']),
  };
}

export function IUpdateTokenGroupDataToJSON(value?: IUpdateTokenGroupData | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    company: value.company,
    tokenGroupDataId: value.tokenGroupDataId,
    reserveTokenDataId: value.reserveTokenDataId,
    reserveTokenDataAmount: value.reserveTokenDataAmount,
    metadata: ITokenDataMetadataToJSON(value.metadata),
  };
}
