/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IVerifyToken
 */
export interface IVerifyToken {
    /**
     * 
     * @type {any}
     * @memberof IVerifyToken
     */
    company?: any | null;
    /**
     * Wallet id of the user you want to link to your client. The user must first have logged in using the Wallet SDK initialized with your companyId.
     * @type {string}
     * @memberof IVerifyToken
     */
    walletId: string;
}

/**
 * Check if a given object implements the IVerifyToken interface.
 */
export function instanceOfIVerifyToken(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "walletId" in value;

    return isInstance;
}

export function IVerifyTokenFromJSON(json: any): IVerifyToken {
    return IVerifyTokenFromJSONTyped(json, false);
}

export function IVerifyTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): IVerifyToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'company': !exists(json, 'company') ? undefined : json['company'],
        'walletId': json['walletId'],
    };
}

export function IVerifyTokenToJSON(value?: IVerifyToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'company': value.company,
        'walletId': value.walletId,
    };
}

