/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface IWalletResetPassword
 */
export interface IWalletResetPassword {
  /**
   *
   * @type {string}
   * @memberof IWalletResetPassword
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof IWalletResetPassword
   */
  token: string;
}

/**
 * Check if a given object implements the IWalletResetPassword interface.
 */
export function instanceOfIWalletResetPassword(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'password' in value;
  isInstance = isInstance && 'token' in value;

  return isInstance;
}

export function IWalletResetPasswordFromJSON(json: any): IWalletResetPassword {
  return IWalletResetPasswordFromJSONTyped(json, false);
}

export function IWalletResetPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): IWalletResetPassword {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    password: json['password'],
    token: json['token'],
  };
}

export function IWalletResetPasswordToJSON(value?: IWalletResetPassword | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    password: value.password,
    token: value.token,
  };
}
