/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IWalletCustomAuth
 */
export interface IWalletCustomAuth {
    /**
     * 
     * @type {string}
     * @memberof IWalletCustomAuth
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof IWalletCustomAuth
     */
    password: string;
}

/**
 * Check if a given object implements the IWalletCustomAuth interface.
 */
export function instanceOfIWalletCustomAuth(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function IWalletCustomAuthFromJSON(json: any): IWalletCustomAuth {
    return IWalletCustomAuthFromJSONTyped(json, false);
}

export function IWalletCustomAuthFromJSONTyped(json: any, ignoreDiscriminator: boolean): IWalletCustomAuth {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function IWalletCustomAuthToJSON(value?: IWalletCustomAuth | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}

