/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface IWalletSign
 */
export interface IWalletSign {
  /**
   *
   * @type {any}
   * @memberof IWalletSign
   */
  company?: any | null;
  /**
   *
   * @type {string}
   * @memberof IWalletSign
   */
  walletId: string;
  /**
   *
   * @type {string}
   * @memberof IWalletSign
   */
  message: string;
}

/**
 * Check if a given object implements the IWalletSign interface.
 */
export function instanceOfIWalletSign(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'walletId' in value;
  isInstance = isInstance && 'message' in value;

  return isInstance;
}

export function IWalletSignFromJSON(json: any): IWalletSign {
  return IWalletSignFromJSONTyped(json, false);
}

export function IWalletSignFromJSONTyped(json: any, ignoreDiscriminator: boolean): IWalletSign {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    company: !exists(json, 'company') ? undefined : json['company'],
    walletId: json['walletId'],
    message: json['message'],
  };
}

export function IWalletSignToJSON(value?: IWalletSign | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    company: value.company,
    walletId: value.walletId,
    message: value.message,
  };
}
