/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MarketPlaceOrderTypesEnum = {
    EnglishAuction: 'ENGLISH_AUCTION',
    None: 'NONE',
    DirectSale: 'DIRECT_SALE',
    MintDirectSale: 'MINT_DIRECT_SALE'
} as const;
export type MarketPlaceOrderTypesEnum = typeof MarketPlaceOrderTypesEnum[keyof typeof MarketPlaceOrderTypesEnum];


export function MarketPlaceOrderTypesEnumFromJSON(json: any): MarketPlaceOrderTypesEnum {
    return MarketPlaceOrderTypesEnumFromJSONTyped(json, false);
}

export function MarketPlaceOrderTypesEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketPlaceOrderTypesEnum {
    return json as MarketPlaceOrderTypesEnum;
}

export function MarketPlaceOrderTypesEnumToJSON(value?: MarketPlaceOrderTypesEnum | null): any {
    return value as any;
}

