/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IListSellOrdersDataResp } from './IListSellOrdersDataResp';
import {
  IListSellOrdersDataRespFromJSON,
  IListSellOrdersDataRespFromJSONTyped,
  IListSellOrdersDataRespToJSON,
} from './IListSellOrdersDataResp';

/**
 *
 * @export
 * @interface ResponsesIListSellOrdersDataResp
 */
export interface ResponsesIListSellOrdersDataResp {
  /**
   *
   * @type {IListSellOrdersDataResp}
   * @memberof ResponsesIListSellOrdersDataResp
   */
  data: IListSellOrdersDataResp;
  /**
   *
   * @type {boolean}
   * @memberof ResponsesIListSellOrdersDataResp
   */
  success: boolean;
  /**
   *
   * @type {string}
   * @memberof ResponsesIListSellOrdersDataResp
   */
  message: string;
}

/**
 * Check if a given object implements the ResponsesIListSellOrdersDataResp interface.
 */
export function instanceOfResponsesIListSellOrdersDataResp(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'data' in value;
  isInstance = isInstance && 'success' in value;
  isInstance = isInstance && 'message' in value;

  return isInstance;
}

export function ResponsesIListSellOrdersDataRespFromJSON(json: any): ResponsesIListSellOrdersDataResp {
  return ResponsesIListSellOrdersDataRespFromJSONTyped(json, false);
}

export function ResponsesIListSellOrdersDataRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResponsesIListSellOrdersDataResp {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: IListSellOrdersDataRespFromJSON(json['data']),
    success: json['success'],
    message: json['message'],
  };
}

export function ResponsesIListSellOrdersDataRespToJSON(value?: ResponsesIListSellOrdersDataResp | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: IListSellOrdersDataRespToJSON(value.data),
    success: value.success,
    message: value.message,
  };
}
