/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ICreateTokenTransferResp } from './ICreateTokenTransferResp';
import {
  ICreateTokenTransferRespFromJSON,
  ICreateTokenTransferRespFromJSONTyped,
  ICreateTokenTransferRespToJSON,
} from './ICreateTokenTransferResp';

/**
 *
 * @export
 * @interface ResponsesICreateTokenTransferResp
 */
export interface ResponsesICreateTokenTransferResp {
  /**
   *
   * @type {ICreateTokenTransferResp}
   * @memberof ResponsesICreateTokenTransferResp
   */
  data: ICreateTokenTransferResp;
  /**
   *
   * @type {boolean}
   * @memberof ResponsesICreateTokenTransferResp
   */
  success: boolean;
  /**
   *
   * @type {string}
   * @memberof ResponsesICreateTokenTransferResp
   */
  message: string;
}

/**
 * Check if a given object implements the ResponsesICreateTokenTransferResp interface.
 */
export function instanceOfResponsesICreateTokenTransferResp(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'data' in value;
  isInstance = isInstance && 'success' in value;
  isInstance = isInstance && 'message' in value;

  return isInstance;
}

export function ResponsesICreateTokenTransferRespFromJSON(json: any): ResponsesICreateTokenTransferResp {
  return ResponsesICreateTokenTransferRespFromJSONTyped(json, false);
}

export function ResponsesICreateTokenTransferRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResponsesICreateTokenTransferResp {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: ICreateTokenTransferRespFromJSON(json['data']),
    success: json['success'],
    message: json['message'],
  };
}

export function ResponsesICreateTokenTransferRespToJSON(value?: ResponsesICreateTokenTransferResp | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: ICreateTokenTransferRespToJSON(value.data),
    success: value.success,
    message: value.message,
  };
}
