/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IWalletLoginResponse } from './IWalletLoginResponse';
import {
    IWalletLoginResponseFromJSON,
    IWalletLoginResponseFromJSONTyped,
    IWalletLoginResponseToJSON,
} from './IWalletLoginResponse';

/**
 * 
 * @export
 * @interface ResponsesIWalletLoginResponse
 */
export interface ResponsesIWalletLoginResponse {
    /**
     * 
     * @type {IWalletLoginResponse}
     * @memberof ResponsesIWalletLoginResponse
     */
    data: IWalletLoginResponse;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsesIWalletLoginResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResponsesIWalletLoginResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ResponsesIWalletLoginResponse interface.
 */
export function instanceOfResponsesIWalletLoginResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ResponsesIWalletLoginResponseFromJSON(json: any): ResponsesIWalletLoginResponse {
    return ResponsesIWalletLoginResponseFromJSONTyped(json, false);
}

export function ResponsesIWalletLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesIWalletLoginResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': IWalletLoginResponseFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
    };
}

export function ResponsesIWalletLoginResponseToJSON(value?: ResponsesIWalletLoginResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': IWalletLoginResponseToJSON(value.data),
        'success': value.success,
        'message': value.message,
    };
}

