/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IListTokenGroupDataResp } from './IListTokenGroupDataResp';
import {
  IListTokenGroupDataRespFromJSON,
  IListTokenGroupDataRespFromJSONTyped,
  IListTokenGroupDataRespToJSON,
} from './IListTokenGroupDataResp';

/**
 *
 * @export
 * @interface ResponsesIListTokenGroupDataResp
 */
export interface ResponsesIListTokenGroupDataResp {
  /**
   *
   * @type {IListTokenGroupDataResp}
   * @memberof ResponsesIListTokenGroupDataResp
   */
  data: IListTokenGroupDataResp;
  /**
   *
   * @type {boolean}
   * @memberof ResponsesIListTokenGroupDataResp
   */
  success: boolean;
  /**
   *
   * @type {string}
   * @memberof ResponsesIListTokenGroupDataResp
   */
  message: string;
}

/**
 * Check if a given object implements the ResponsesIListTokenGroupDataResp interface.
 */
export function instanceOfResponsesIListTokenGroupDataResp(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'data' in value;
  isInstance = isInstance && 'success' in value;
  isInstance = isInstance && 'message' in value;

  return isInstance;
}

export function ResponsesIListTokenGroupDataRespFromJSON(json: any): ResponsesIListTokenGroupDataResp {
  return ResponsesIListTokenGroupDataRespFromJSONTyped(json, false);
}

export function ResponsesIListTokenGroupDataRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResponsesIListTokenGroupDataResp {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: IListTokenGroupDataRespFromJSON(json['data']),
    success: json['success'],
    message: json['message'],
  };
}

export function ResponsesIListTokenGroupDataRespToJSON(value?: ResponsesIListTokenGroupDataResp | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: IListTokenGroupDataRespToJSON(value.data),
    success: value.success,
    message: value.message,
  };
}
