/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResponseTokenData } from './ResponseTokenData';
import {
    ResponseTokenDataFromJSON,
    ResponseTokenDataFromJSONTyped,
    ResponseTokenDataToJSON,
} from './ResponseTokenData';

/**
 * 
 * @export
 * @interface ResponseListOwnedNFTElement
 */
export interface ResponseListOwnedNFTElement {
    /**
     * 
     * @type {ResponseTokenData}
     * @memberof ResponseListOwnedNFTElement
     */
    token: ResponseTokenData;
    /**
     * 
     * @type {string}
     * @memberof ResponseListOwnedNFTElement
     */
    quantity: string;
}

/**
 * Check if a given object implements the ResponseListOwnedNFTElement interface.
 */
export function instanceOfResponseListOwnedNFTElement(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;
    isInstance = isInstance && "quantity" in value;

    return isInstance;
}

export function ResponseListOwnedNFTElementFromJSON(json: any): ResponseListOwnedNFTElement {
    return ResponseListOwnedNFTElementFromJSONTyped(json, false);
}

export function ResponseListOwnedNFTElementFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseListOwnedNFTElement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': ResponseTokenDataFromJSON(json['token']),
        'quantity': json['quantity'],
    };
}

export function ResponseListOwnedNFTElementToJSON(value?: ResponseListOwnedNFTElement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': ResponseTokenDataToJSON(value.token),
        'quantity': value.quantity,
    };
}

