/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResponseTokenData } from './ResponseTokenData';
import {
    ResponseTokenDataFromJSON,
    ResponseTokenDataFromJSONTyped,
    ResponseTokenDataToJSON,
} from './ResponseTokenData';

/**
 * 
 * @export
 * @interface ResponseITokenData
 */
export interface ResponseITokenData {
    /**
     * 
     * @type {ResponseTokenData}
     * @memberof ResponseITokenData
     */
    token: ResponseTokenData;
    /**
     * 
     * @type {string}
     * @memberof ResponseITokenData
     */
    lastId: string;
}

/**
 * Check if a given object implements the ResponseITokenData interface.
 */
export function instanceOfResponseITokenData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;
    isInstance = isInstance && "lastId" in value;

    return isInstance;
}

export function ResponseITokenDataFromJSON(json: any): ResponseITokenData {
    return ResponseITokenDataFromJSONTyped(json, false);
}

export function ResponseITokenDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseITokenData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': ResponseTokenDataFromJSON(json['token']),
        'lastId': json['lastId'],
    };
}

export function ResponseITokenDataToJSON(value?: ResponseITokenData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': ResponseTokenDataToJSON(value.token),
        'lastId': value.lastId,
    };
}

