/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ISubmitTokenTransferResp } from './ISubmitTokenTransferResp';
import {
  ISubmitTokenTransferRespFromJSON,
  ISubmitTokenTransferRespFromJSONTyped,
  ISubmitTokenTransferRespToJSON,
} from './ISubmitTokenTransferResp';

/**
 *
 * @export
 * @interface ResponsesISubmitTokenTransferResp
 */
export interface ResponsesISubmitTokenTransferResp {
  /**
   *
   * @type {ISubmitTokenTransferResp}
   * @memberof ResponsesISubmitTokenTransferResp
   */
  data: ISubmitTokenTransferResp;
  /**
   *
   * @type {boolean}
   * @memberof ResponsesISubmitTokenTransferResp
   */
  success: boolean;
  /**
   *
   * @type {string}
   * @memberof ResponsesISubmitTokenTransferResp
   */
  message: string;
}

/**
 * Check if a given object implements the ResponsesISubmitTokenTransferResp interface.
 */
export function instanceOfResponsesISubmitTokenTransferResp(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'data' in value;
  isInstance = isInstance && 'success' in value;
  isInstance = isInstance && 'message' in value;

  return isInstance;
}

export function ResponsesISubmitTokenTransferRespFromJSON(json: any): ResponsesISubmitTokenTransferResp {
  return ResponsesISubmitTokenTransferRespFromJSONTyped(json, false);
}

export function ResponsesISubmitTokenTransferRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResponsesISubmitTokenTransferResp {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: ISubmitTokenTransferRespFromJSON(json['data']),
    success: json['success'],
    message: json['message'],
  };
}

export function ResponsesISubmitTokenTransferRespToJSON(value?: ResponsesISubmitTokenTransferResp | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: ISubmitTokenTransferRespToJSON(value.data),
    success: value.success,
    message: value.message,
  };
}
