/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResponseTokenData } from './ResponseTokenData';
import {
  ResponseTokenDataFromJSON,
  ResponseTokenDataFromJSONTyped,
  ResponseTokenDataToJSON,
} from './ResponseTokenData';

/**
 *
 * @export
 * @interface ResponseIListTokenData
 */
export interface ResponseIListTokenData {
  /**
   *
   * @type {Array<ResponseTokenData>}
   * @memberof ResponseIListTokenData
   */
  tokens: Array<ResponseTokenData>;
  /**
   *
   * @type {string}
   * @memberof ResponseIListTokenData
   */
  lastId: string;
}

/**
 * Check if a given object implements the ResponseIListTokenData interface.
 */
export function instanceOfResponseIListTokenData(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'tokens' in value;
  isInstance = isInstance && 'lastId' in value;

  return isInstance;
}

export function ResponseIListTokenDataFromJSON(json: any): ResponseIListTokenData {
  return ResponseIListTokenDataFromJSONTyped(json, false);
}

export function ResponseIListTokenDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseIListTokenData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    tokens: (json['tokens'] as Array<any>).map(ResponseTokenDataFromJSON),
    lastId: json['lastId'],
  };
}

export function ResponseIListTokenDataToJSON(value?: ResponseIListTokenData | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    tokens: (value.tokens as Array<any>).map(ResponseTokenDataToJSON),
    lastId: value.lastId,
  };
}
