/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WalletBalance } from './WalletBalance';
import {
    WalletBalanceFromJSON,
    WalletBalanceFromJSONTyped,
    WalletBalanceToJSON,
} from './WalletBalance';

/**
 * 
 * @export
 * @interface ResponsesWalletBalance
 */
export interface ResponsesWalletBalance {
    /**
     * 
     * @type {WalletBalance}
     * @memberof ResponsesWalletBalance
     */
    data: WalletBalance;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsesWalletBalance
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResponsesWalletBalance
     */
    message: string;
}

/**
 * Check if a given object implements the ResponsesWalletBalance interface.
 */
export function instanceOfResponsesWalletBalance(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ResponsesWalletBalanceFromJSON(json: any): ResponsesWalletBalance {
    return ResponsesWalletBalanceFromJSONTyped(json, false);
}

export function ResponsesWalletBalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesWalletBalance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': WalletBalanceFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
    };
}

export function ResponsesWalletBalanceToJSON(value?: ResponsesWalletBalance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': WalletBalanceToJSON(value.data),
        'success': value.success,
        'message': value.message,
    };
}

