/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResponseIListContracts } from './ResponseIListContracts';
import {
    ResponseIListContractsFromJSON,
    ResponseIListContractsFromJSONTyped,
    ResponseIListContractsToJSON,
} from './ResponseIListContracts';

/**
 * 
 * @export
 * @interface ResponsesResponseIListContracts
 */
export interface ResponsesResponseIListContracts {
    /**
     * 
     * @type {ResponseIListContracts}
     * @memberof ResponsesResponseIListContracts
     */
    data: ResponseIListContracts;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsesResponseIListContracts
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResponsesResponseIListContracts
     */
    message: string;
}

/**
 * Check if a given object implements the ResponsesResponseIListContracts interface.
 */
export function instanceOfResponsesResponseIListContracts(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ResponsesResponseIListContractsFromJSON(json: any): ResponsesResponseIListContracts {
    return ResponsesResponseIListContractsFromJSONTyped(json, false);
}

export function ResponsesResponseIListContractsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesResponseIListContracts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ResponseIListContractsFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
    };
}

export function ResponsesResponseIListContractsToJSON(value?: ResponsesResponseIListContracts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ResponseIListContractsToJSON(value.data),
        'success': value.success,
        'message': value.message,
    };
}

