/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResponseCryptoWallet } from './ResponseCryptoWallet';
import {
  ResponseCryptoWalletFromJSON,
  ResponseCryptoWalletFromJSONTyped,
  ResponseCryptoWalletToJSON,
} from './ResponseCryptoWallet';

/**
 *
 * @export
 * @interface ResponsesResponseCryptoWalletArray
 */
export interface ResponsesResponseCryptoWalletArray {
  /**
   *
   * @type {Array<ResponseCryptoWallet>}
   * @memberof ResponsesResponseCryptoWalletArray
   */
  data: Array<ResponseCryptoWallet>;
  /**
   *
   * @type {boolean}
   * @memberof ResponsesResponseCryptoWalletArray
   */
  success: boolean;
  /**
   *
   * @type {string}
   * @memberof ResponsesResponseCryptoWalletArray
   */
  message: string;
}

/**
 * Check if a given object implements the ResponsesResponseCryptoWalletArray interface.
 */
export function instanceOfResponsesResponseCryptoWalletArray(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'data' in value;
  isInstance = isInstance && 'success' in value;
  isInstance = isInstance && 'message' in value;

  return isInstance;
}

export function ResponsesResponseCryptoWalletArrayFromJSON(json: any): ResponsesResponseCryptoWalletArray {
  return ResponsesResponseCryptoWalletArrayFromJSONTyped(json, false);
}

export function ResponsesResponseCryptoWalletArrayFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResponsesResponseCryptoWalletArray {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(ResponseCryptoWalletFromJSON),
    success: json['success'],
    message: json['message'],
  };
}

export function ResponsesResponseCryptoWalletArrayToJSON(value?: ResponsesResponseCryptoWalletArray | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: (value.data as Array<any>).map(ResponseCryptoWalletToJSON),
    success: value.success,
    message: value.message,
  };
}
