/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WalletBalance } from './WalletBalance';
import {
    WalletBalanceFromJSON,
    WalletBalanceFromJSONTyped,
    WalletBalanceToJSON,
} from './WalletBalance';

/**
 * 
 * @export
 * @interface ResponsesWalletBalanceArray
 */
export interface ResponsesWalletBalanceArray {
    /**
     * 
     * @type {Array<WalletBalance>}
     * @memberof ResponsesWalletBalanceArray
     */
    data: Array<WalletBalance>;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsesWalletBalanceArray
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResponsesWalletBalanceArray
     */
    message: string;
}

/**
 * Check if a given object implements the ResponsesWalletBalanceArray interface.
 */
export function instanceOfResponsesWalletBalanceArray(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ResponsesWalletBalanceArrayFromJSON(json: any): ResponsesWalletBalanceArray {
    return ResponsesWalletBalanceArrayFromJSONTyped(json, false);
}

export function ResponsesWalletBalanceArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesWalletBalanceArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(WalletBalanceFromJSON)),
        'success': json['success'],
        'message': json['message'],
    };
}

export function ResponsesWalletBalanceArrayToJSON(value?: ResponsesWalletBalanceArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(WalletBalanceToJSON)),
        'success': value.success,
        'message': value.message,
    };
}

