/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResponseCompany } from './ResponseCompany';
import {
    ResponseCompanyFromJSON,
    ResponseCompanyFromJSONTyped,
    ResponseCompanyToJSON,
} from './ResponseCompany';

/**
 * 
 * @export
 * @interface ResponsesResponseCompany
 */
export interface ResponsesResponseCompany {
    /**
     * 
     * @type {ResponseCompany}
     * @memberof ResponsesResponseCompany
     */
    data: ResponseCompany;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsesResponseCompany
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResponsesResponseCompany
     */
    message: string;
}

/**
 * Check if a given object implements the ResponsesResponseCompany interface.
 */
export function instanceOfResponsesResponseCompany(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ResponsesResponseCompanyFromJSON(json: any): ResponsesResponseCompany {
    return ResponsesResponseCompanyFromJSONTyped(json, false);
}

export function ResponsesResponseCompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesResponseCompany {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ResponseCompanyFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
    };
}

export function ResponsesResponseCompanyToJSON(value?: ResponsesResponseCompany | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ResponseCompanyToJSON(value.data),
        'success': value.success,
        'message': value.message,
    };
}

