/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponsesCryptoWallet
 */
export interface ResponsesCryptoWallet {
    /**
     * 
     * @type {any}
     * @memberof ResponsesCryptoWallet
     */
    data: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsesCryptoWallet
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResponsesCryptoWallet
     */
    message: string;
}

/**
 * Check if a given object implements the ResponsesCryptoWallet interface.
 */
export function instanceOfResponsesCryptoWallet(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ResponsesCryptoWalletFromJSON(json: any): ResponsesCryptoWallet {
    return ResponsesCryptoWalletFromJSONTyped(json, false);
}

export function ResponsesCryptoWalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesCryptoWallet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': json['data'],
        'success': json['success'],
        'message': json['message'],
    };
}

export function ResponsesCryptoWalletToJSON(value?: ResponsesCryptoWallet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
        'success': value.success,
        'message': value.message,
    };
}

