/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResponseContract } from './ResponseContract';
import { ResponseContractFromJSON, ResponseContractFromJSONTyped, ResponseContractToJSON } from './ResponseContract';

/**
 *
 * @export
 * @interface ResponsesResponseContract
 */
export interface ResponsesResponseContract {
  /**
   *
   * @type {ResponseContract}
   * @memberof ResponsesResponseContract
   */
  data: ResponseContract;
  /**
   *
   * @type {boolean}
   * @memberof ResponsesResponseContract
   */
  success: boolean;
  /**
   *
   * @type {string}
   * @memberof ResponsesResponseContract
   */
  message: string;
}

/**
 * Check if a given object implements the ResponsesResponseContract interface.
 */
export function instanceOfResponsesResponseContract(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'data' in value;
  isInstance = isInstance && 'success' in value;
  isInstance = isInstance && 'message' in value;

  return isInstance;
}

export function ResponsesResponseContractFromJSON(json: any): ResponsesResponseContract {
  return ResponsesResponseContractFromJSONTyped(json, false);
}

export function ResponsesResponseContractFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResponsesResponseContract {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: ResponseContractFromJSON(json['data']),
    success: json['success'],
    message: json['message'],
  };
}

export function ResponsesResponseContractToJSON(value?: ResponsesResponseContract | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: ResponseContractToJSON(value.data),
    success: value.success,
    message: value.message,
  };
}
