/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IGetWalletResp } from './IGetWalletResp';
import {
    IGetWalletRespFromJSON,
    IGetWalletRespFromJSONTyped,
    IGetWalletRespToJSON,
} from './IGetWalletResp';

/**
 * 
 * @export
 * @interface ResponsesIGetWalletResp
 */
export interface ResponsesIGetWalletResp {
    /**
     * 
     * @type {IGetWalletResp}
     * @memberof ResponsesIGetWalletResp
     */
    data: IGetWalletResp;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsesIGetWalletResp
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResponsesIGetWalletResp
     */
    message: string;
}

/**
 * Check if a given object implements the ResponsesIGetWalletResp interface.
 */
export function instanceOfResponsesIGetWalletResp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ResponsesIGetWalletRespFromJSON(json: any): ResponsesIGetWalletResp {
    return ResponsesIGetWalletRespFromJSONTyped(json, false);
}

export function ResponsesIGetWalletRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesIGetWalletResp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': IGetWalletRespFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
    };
}

export function ResponsesIGetWalletRespToJSON(value?: ResponsesIGetWalletResp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': IGetWalletRespToJSON(value.data),
        'success': value.success,
        'message': value.message,
    };
}

