/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ISignMarketplaceOrderString } from './ISignMarketplaceOrderString';
import {
  ISignMarketplaceOrderStringFromJSON,
  ISignMarketplaceOrderStringFromJSONTyped,
  ISignMarketplaceOrderStringToJSON,
} from './ISignMarketplaceOrderString';

/**
 *
 * @export
 * @interface ResponsesISignMarketplaceOrderString
 */
export interface ResponsesISignMarketplaceOrderString {
  /**
   *
   * @type {ISignMarketplaceOrderString}
   * @memberof ResponsesISignMarketplaceOrderString
   */
  data: ISignMarketplaceOrderString;
  /**
   *
   * @type {boolean}
   * @memberof ResponsesISignMarketplaceOrderString
   */
  success: boolean;
  /**
   *
   * @type {string}
   * @memberof ResponsesISignMarketplaceOrderString
   */
  message: string;
}

/**
 * Check if a given object implements the ResponsesISignMarketplaceOrderString interface.
 */
export function instanceOfResponsesISignMarketplaceOrderString(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'data' in value;
  isInstance = isInstance && 'success' in value;
  isInstance = isInstance && 'message' in value;

  return isInstance;
}

export function ResponsesISignMarketplaceOrderStringFromJSON(json: any): ResponsesISignMarketplaceOrderString {
  return ResponsesISignMarketplaceOrderStringFromJSONTyped(json, false);
}

export function ResponsesISignMarketplaceOrderStringFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResponsesISignMarketplaceOrderString {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: ISignMarketplaceOrderStringFromJSON(json['data']),
    success: json['success'],
    message: json['message'],
  };
}

export function ResponsesISignMarketplaceOrderStringToJSON(value?: ResponsesISignMarketplaceOrderString | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: ISignMarketplaceOrderStringToJSON(value.data),
    success: value.success,
    message: value.message,
  };
}
