/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ISubmitBuyOrderResponse } from './ISubmitBuyOrderResponse';
import {
  ISubmitBuyOrderResponseFromJSON,
  ISubmitBuyOrderResponseFromJSONTyped,
  ISubmitBuyOrderResponseToJSON,
} from './ISubmitBuyOrderResponse';

/**
 *
 * @export
 * @interface ResponsesISubmitBuyOrderResponse
 */
export interface ResponsesISubmitBuyOrderResponse {
  /**
   *
   * @type {ISubmitBuyOrderResponse}
   * @memberof ResponsesISubmitBuyOrderResponse
   */
  data: ISubmitBuyOrderResponse;
  /**
   *
   * @type {boolean}
   * @memberof ResponsesISubmitBuyOrderResponse
   */
  success: boolean;
  /**
   *
   * @type {string}
   * @memberof ResponsesISubmitBuyOrderResponse
   */
  message: string;
}

/**
 * Check if a given object implements the ResponsesISubmitBuyOrderResponse interface.
 */
export function instanceOfResponsesISubmitBuyOrderResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'data' in value;
  isInstance = isInstance && 'success' in value;
  isInstance = isInstance && 'message' in value;

  return isInstance;
}

export function ResponsesISubmitBuyOrderResponseFromJSON(json: any): ResponsesISubmitBuyOrderResponse {
  return ResponsesISubmitBuyOrderResponseFromJSONTyped(json, false);
}

export function ResponsesISubmitBuyOrderResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResponsesISubmitBuyOrderResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: ISubmitBuyOrderResponseFromJSON(json['data']),
    success: json['success'],
    message: json['message'],
  };
}

export function ResponsesISubmitBuyOrderResponseToJSON(value?: ResponsesISubmitBuyOrderResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: ISubmitBuyOrderResponseToJSON(value.data),
    success: value.success,
    message: value.message,
  };
}
