/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IGetTokenGroupDataResp } from './IGetTokenGroupDataResp';
import {
    IGetTokenGroupDataRespFromJSON,
    IGetTokenGroupDataRespFromJSONTyped,
    IGetTokenGroupDataRespToJSON,
} from './IGetTokenGroupDataResp';

/**
 * 
 * @export
 * @interface ResponsesIGetTokenGroupDataResp
 */
export interface ResponsesIGetTokenGroupDataResp {
    /**
     * 
     * @type {IGetTokenGroupDataResp}
     * @memberof ResponsesIGetTokenGroupDataResp
     */
    data: IGetTokenGroupDataResp;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsesIGetTokenGroupDataResp
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResponsesIGetTokenGroupDataResp
     */
    message: string;
}

/**
 * Check if a given object implements the ResponsesIGetTokenGroupDataResp interface.
 */
export function instanceOfResponsesIGetTokenGroupDataResp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ResponsesIGetTokenGroupDataRespFromJSON(json: any): ResponsesIGetTokenGroupDataResp {
    return ResponsesIGetTokenGroupDataRespFromJSONTyped(json, false);
}

export function ResponsesIGetTokenGroupDataRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesIGetTokenGroupDataResp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': IGetTokenGroupDataRespFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
    };
}

export function ResponsesIGetTokenGroupDataRespToJSON(value?: ResponsesIGetTokenGroupDataResp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': IGetTokenGroupDataRespToJSON(value.data),
        'success': value.success,
        'message': value.message,
    };
}

