/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IListBuyOrdersDataResp } from './IListBuyOrdersDataResp';
import {
    IListBuyOrdersDataRespFromJSON,
    IListBuyOrdersDataRespFromJSONTyped,
    IListBuyOrdersDataRespToJSON,
} from './IListBuyOrdersDataResp';

/**
 * 
 * @export
 * @interface ResponsesIListBuyOrdersDataResp
 */
export interface ResponsesIListBuyOrdersDataResp {
    /**
     * 
     * @type {IListBuyOrdersDataResp}
     * @memberof ResponsesIListBuyOrdersDataResp
     */
    data: IListBuyOrdersDataResp;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsesIListBuyOrdersDataResp
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResponsesIListBuyOrdersDataResp
     */
    message: string;
}

/**
 * Check if a given object implements the ResponsesIListBuyOrdersDataResp interface.
 */
export function instanceOfResponsesIListBuyOrdersDataResp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ResponsesIListBuyOrdersDataRespFromJSON(json: any): ResponsesIListBuyOrdersDataResp {
    return ResponsesIListBuyOrdersDataRespFromJSONTyped(json, false);
}

export function ResponsesIListBuyOrdersDataRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesIListBuyOrdersDataResp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': IListBuyOrdersDataRespFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
    };
}

export function ResponsesIListBuyOrdersDataRespToJSON(value?: ResponsesIListBuyOrdersDataResp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': IListBuyOrdersDataRespToJSON(value.data),
        'success': value.success,
        'message': value.message,
    };
}

