/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResponseIListTokenData } from './ResponseIListTokenData';
import {
    ResponseIListTokenDataFromJSON,
    ResponseIListTokenDataFromJSONTyped,
    ResponseIListTokenDataToJSON,
} from './ResponseIListTokenData';

/**
 * 
 * @export
 * @interface ResponsesResponseIListTokenData
 */
export interface ResponsesResponseIListTokenData {
    /**
     * 
     * @type {ResponseIListTokenData}
     * @memberof ResponsesResponseIListTokenData
     */
    data: ResponseIListTokenData;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsesResponseIListTokenData
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResponsesResponseIListTokenData
     */
    message: string;
}

/**
 * Check if a given object implements the ResponsesResponseIListTokenData interface.
 */
export function instanceOfResponsesResponseIListTokenData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ResponsesResponseIListTokenDataFromJSON(json: any): ResponsesResponseIListTokenData {
    return ResponsesResponseIListTokenDataFromJSONTyped(json, false);
}

export function ResponsesResponseIListTokenDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesResponseIListTokenData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ResponseIListTokenDataFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
    };
}

export function ResponsesResponseIListTokenDataToJSON(value?: ResponsesResponseIListTokenData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ResponseIListTokenDataToJSON(value.data),
        'success': value.success,
        'message': value.message,
    };
}

