/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResponseTokenData } from './ResponseTokenData';
import {
  ResponseTokenDataFromJSON,
  ResponseTokenDataFromJSONTyped,
  ResponseTokenDataToJSON,
} from './ResponseTokenData';

/**
 *
 * @export
 * @interface ResponsesResponseTokenData
 */
export interface ResponsesResponseTokenData {
  /**
   *
   * @type {ResponseTokenData}
   * @memberof ResponsesResponseTokenData
   */
  data: ResponseTokenData;
  /**
   *
   * @type {boolean}
   * @memberof ResponsesResponseTokenData
   */
  success: boolean;
  /**
   *
   * @type {string}
   * @memberof ResponsesResponseTokenData
   */
  message: string;
}

/**
 * Check if a given object implements the ResponsesResponseTokenData interface.
 */
export function instanceOfResponsesResponseTokenData(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'data' in value;
  isInstance = isInstance && 'success' in value;
  isInstance = isInstance && 'message' in value;

  return isInstance;
}

export function ResponsesResponseTokenDataFromJSON(json: any): ResponsesResponseTokenData {
  return ResponsesResponseTokenDataFromJSONTyped(json, false);
}

export function ResponsesResponseTokenDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResponsesResponseTokenData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: ResponseTokenDataFromJSON(json['data']),
    success: json['success'],
    message: json['message'],
  };
}

export function ResponsesResponseTokenDataToJSON(value?: ResponsesResponseTokenData | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: ResponseTokenDataToJSON(value.data),
    success: value.success,
    message: value.message,
  };
}
