/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IRefreshTokenResponse } from './IRefreshTokenResponse';
import {
    IRefreshTokenResponseFromJSON,
    IRefreshTokenResponseFromJSONTyped,
    IRefreshTokenResponseToJSON,
} from './IRefreshTokenResponse';

/**
 * 
 * @export
 * @interface ResponsesIRefreshTokenResponse
 */
export interface ResponsesIRefreshTokenResponse {
    /**
     * 
     * @type {IRefreshTokenResponse}
     * @memberof ResponsesIRefreshTokenResponse
     */
    data: IRefreshTokenResponse;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsesIRefreshTokenResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResponsesIRefreshTokenResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ResponsesIRefreshTokenResponse interface.
 */
export function instanceOfResponsesIRefreshTokenResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ResponsesIRefreshTokenResponseFromJSON(json: any): ResponsesIRefreshTokenResponse {
    return ResponsesIRefreshTokenResponseFromJSONTyped(json, false);
}

export function ResponsesIRefreshTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesIRefreshTokenResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': IRefreshTokenResponseFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
    };
}

export function ResponsesIRefreshTokenResponseToJSON(value?: ResponsesIRefreshTokenResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': IRefreshTokenResponseToJSON(value.data),
        'success': value.success,
        'message': value.message,
    };
}

