/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IWalletAuthResponse } from './IWalletAuthResponse';
import {
  IWalletAuthResponseFromJSON,
  IWalletAuthResponseFromJSONTyped,
  IWalletAuthResponseToJSON,
} from './IWalletAuthResponse';

/**
 *
 * @export
 * @interface ResponsesIWalletAuthResponse
 */
export interface ResponsesIWalletAuthResponse {
  /**
   *
   * @type {IWalletAuthResponse}
   * @memberof ResponsesIWalletAuthResponse
   */
  data: IWalletAuthResponse;
  /**
   *
   * @type {boolean}
   * @memberof ResponsesIWalletAuthResponse
   */
  success: boolean;
  /**
   *
   * @type {string}
   * @memberof ResponsesIWalletAuthResponse
   */
  message: string;
}

/**
 * Check if a given object implements the ResponsesIWalletAuthResponse interface.
 */
export function instanceOfResponsesIWalletAuthResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'data' in value;
  isInstance = isInstance && 'success' in value;
  isInstance = isInstance && 'message' in value;

  return isInstance;
}

export function ResponsesIWalletAuthResponseFromJSON(json: any): ResponsesIWalletAuthResponse {
  return ResponsesIWalletAuthResponseFromJSONTyped(json, false);
}

export function ResponsesIWalletAuthResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResponsesIWalletAuthResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: IWalletAuthResponseFromJSON(json['data']),
    success: json['success'],
    message: json['message'],
  };
}

export function ResponsesIWalletAuthResponseToJSON(value?: ResponsesIWalletAuthResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: IWalletAuthResponseToJSON(value.data),
    success: value.success,
    message: value.message,
  };
}
