/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TokenDataType = {
    Eth: 'ETH',
    Erc20: 'ERC20',
    Erc721: 'ERC721',
    Erc721Lazy: 'ERC721_LAZY',
    Erc1155: 'ERC1155',
    Erc1155Lazy: 'ERC1155_LAZY'
} as const;
export type TokenDataType = typeof TokenDataType[keyof typeof TokenDataType];


export function TokenDataTypeFromJSON(json: any): TokenDataType {
    return TokenDataTypeFromJSONTyped(json, false);
}

export function TokenDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenDataType {
    return json as TokenDataType;
}

export function TokenDataTypeToJSON(value?: TokenDataType | null): any {
    return value as any;
}

