/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WalletBalance
 */
export interface WalletBalance {
    /**
     * 
     * @type {string}
     * @memberof WalletBalance
     */
    balance: string;
    /**
     * 
     * @type {number}
     * @memberof WalletBalance
     */
    decimals: number;
    /**
     * 
     * @type {string}
     * @memberof WalletBalance
     */
    symbol: string;
    /**
     * 
     * @type {string}
     * @memberof WalletBalance
     */
    rawBalance: string;
    /**
     * 
     * @type {string}
     * @memberof WalletBalance
     */
    chain?: string;
}

/**
 * Check if a given object implements the WalletBalance interface.
 */
export function instanceOfWalletBalance(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "balance" in value;
    isInstance = isInstance && "decimals" in value;
    isInstance = isInstance && "symbol" in value;
    isInstance = isInstance && "rawBalance" in value;

    return isInstance;
}

export function WalletBalanceFromJSON(json: any): WalletBalance {
    return WalletBalanceFromJSONTyped(json, false);
}

export function WalletBalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletBalance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'balance': json['balance'],
        'decimals': json['decimals'],
        'symbol': json['symbol'],
        'rawBalance': json['rawBalance'],
        'chain': !exists(json, 'chain') ? undefined : json['chain'],
    };
}

export function WalletBalanceToJSON(value?: WalletBalance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'balance': value.balance,
        'decimals': value.decimals,
        'symbol': value.symbol,
        'rawBalance': value.rawBalance,
        'chain': value.chain,
    };
}

