/* tslint:disable */
/* eslint-disable */
/**
 * namaste-be
 * Namaste Server
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const WalletRegistrationStatus = {
  Verified: 'VERIFIED',
  NotVerified: 'NOT_VERIFIED',
  None: 'NONE',
} as const;
export type WalletRegistrationStatus = typeof WalletRegistrationStatus[keyof typeof WalletRegistrationStatus];

export function WalletRegistrationStatusFromJSON(json: any): WalletRegistrationStatus {
  return WalletRegistrationStatusFromJSONTyped(json, false);
}

export function WalletRegistrationStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WalletRegistrationStatus {
  return json as WalletRegistrationStatus;
}

export function WalletRegistrationStatusToJSON(value?: WalletRegistrationStatus | null): any {
  return value as any;
}
